#!/bin/bash
# Docker Hub post_push hook that is responsible to tag built image properly.

set -e

# Parse image name and tag.
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
origTag=${IMAGE_NAME:tagStart}

fullOs=stretch-slim

# Re-tag beta images.
if [[ "$origTag" == "beta-$fullOs" ]]; then
  fullVer=$(docker run --rm $repoName:$origTag rustc -V \
                                               | cut -d ' ' -f2 \
                                               | tr -d "\n ")
  numVer=$(echo "$fullVer" | cut -d '-' -f1 | tr -d "\n ")

  for ver in {$fullVer,$numVer-beta,beta}; do
    for os in {-$fullOs,}; do
      tag=$ver$os
      docker tag $repoName:$origTag $repoName:$tag
      docker push $repoName:$tag
    done
  done
fi
