#!/bin/bash
# Docker Hub post-push hook that is responsible to tag built image properly.

set -e

# Parse image name and tag.
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}
origTag=${IMAGE_NAME:tagStart}

# Re-push nightly-slim images from official rustlang/rust repo with preserving
# concrete nightly version.
if [[ "$origTag" == "nightly-slim" ]]; then
    docker pull rustlang/rust:nightly-slim
    dateVer=$(docker run --rm rustlang/rust:nightly-slim rustc -V \
                     | cut -d ' ' -f4 \
                     | tr -d "\n )")
    docker tag rustlang/rust:nightly-slim ${repoName}:nightly-slim-${dateVer}
    docker tag rustlang/rust:nightly-slim ${repoName}:nightly-slim
    docker push ${repoName}:nightly-slim-${dateVer}
    docker push ${repoName}:nightly-slim
fi
