name: Nightly CI

on:
  schedule:
    - cron: "*/30 * * * *"

env:
  NAME: rust
  REGISTRY_AUTH_FILE: ./auth.json

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        registry: ["ghcr.io", "docker.io", "quay.io"]
        os:
          - alpine3.15
          - alpine3.14
          - buster
          - buster-slim
          - bullseye
          - bullseye-slim
        include:
          - os: alpine3.15
            tags: |
              nightly-alpine3.15-<ver>
              nightly-alpine-<ver>
              nightly-alpine3.15
              nightly-alpine
          - os: alpine3.14
            tags: |
              nightly-alpine3.14-<ver>
              nightly-alpine3.14
          - os: buster
            tags: |
              nightly-buster-<ver>
              nightly-<ver>
              nightly-buster
              nightly
          - os: buster-slim
            tags: |
              nightly-buster-slim-<ver>
              nightly-slim-<ver>
              nightly-buster-slim
              nightly-slim
          - os: bullseye
            tags: |
              nightly-bullseye-<ver>
              nightly-bullseye
          - os: bullseye-slim
            tags: |
              nightly-bullseye-slim-<ver>
              nightly-bullseye-slim
    steps:
      # Skip if this is fork and no credentials are provided.
      - id: skip
        run: echo ::set-output name=no::${{ !(
               github.repository_owner != 'instrumentisto'
               && ((matrix.registry == 'quay.io'
                    && secrets.QUAYIO_ROBOT_USER == '')
                || (matrix.registry == 'docker.io'
                    && secrets.DOCKERHUB_BOT_USER == ''))
             ) }}

      - uses: actions/checkout@v3
        if: ${{ steps.skip.outputs.no == 'true' }}

      - name: Check upstream manifests changed
        id: upstream
        run: echo ::set-output name=RESULT::$(bash nightly/check-changed.sh)
        env:
          IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ env.NAME }}
          IMAGE_OS: ${{ matrix.os }}
        if: ${{ steps.skip.outputs.no == 'true' }}

      - name: Login to ${{ matrix.registry }} container registry
        run: skopeo login --username='${{ (matrix.registry == 'docker.io'
                                           && secrets.DOCKERHUB_BOT_USER)
                                       || (matrix.registry == 'quay.io'
                                           && secrets.QUAYIO_ROBOT_USER)
                                       || github.repository_owner }}'
                          --password='${{ (matrix.registry == 'docker.io'
                                           && secrets.DOCKERHUB_BOT_PASS)
                                       || (matrix.registry == 'quay.io'
                                           && secrets.QUAYIO_ROBOT_TOKEN)
                                       || secrets.GITHUB_TOKEN }}'
                    ${{ matrix.registry }}
        if: ${{ steps.skip.outputs.no == 'true'
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      - name: Copy image
        run: bash nightly/copy.sh
        env:
          IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ env.NAME }}
          IMAGE_OS: ${{ matrix.os }}
          IMAGE_TAGS: ${{ matrix.tags }}
        if: ${{ steps.skip.outputs.no == 'true'
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      - name: Logout from ${{ matrix.registry }} container registry
        run: skopeo logout ${{ matrix.registry }}
        if: ${{ always()
                && steps.skip.outputs.no == 'true'
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
