name: Nightly CI

on:
  schedule:
    - cron: "*/10 * * * *"

env:
  REGISTRIES: ghcr.io,docker.io,quay.io
  REGISTRY_AUTH_FILE: ./auth.json

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: alpine3.15
            tags: |
              nightly-alpine3.15-<ver>
              nightly-alpine-<ver>
              nightly-alpine3.15
              nightly-alpine
          - os: alpine3.14
            tags: |
              nightly-alpine3.14-<ver>
              nightly-alpine3.14
          - os: buster
            tags: |
              nightly-buster-<ver>
              nightly-<ver>
              nightly-buster
              nightly
          - os: buster-slim
            tags: |
              nightly-buster-slim-<ver>
              nightly-slim-<ver>
              nightly-buster-slim
              nightly-slim
          - os: bullseye
            tags: |
              nightly-bullseye-<ver>
              nightly-bullseye
          - os: bullseye-slim
            tags: |
              nightly-bullseye-slim-<ver>
              nightly-bullseye-slim
    steps:
      - uses: actions/checkout@v3

      - name: Check upstream manifests changed
        id: upstream
        run: echo ::set-output name=RESULT::$(bash nightly/check-changed.sh)
        env:
          IMAGE_OS: ${{ matrix.os }}

      - name: Login to GitHub Container Registry
        run: skopeo login --username=${{ github.repository_owner }}
                          --password='${{ secrets.GITHUB_TOKEN }}'
                    ghcr.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Login to Quay.io
        run: skopeo login --username=instrumentisto+bot
                          --password='${{ secrets.QUAYIO_ROBOT_TOKEN }}'
                    quay.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Login to Docker Hub
        run: skopeo login --username=instrumentistobot
                          --password='${{ secrets.DOCKERHUB_BOT_PASS }}'
                    docker.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      # https://github.com/containers/podman/issues/10112
      - name: Fix Podman's containers storage
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\""\
                 > ~/.config/containers/storage.conf

      - name: Copy image
        run: bash nightly/copy.sh
        env:
          IMAGE_OS: ${{ matrix.os }}
          IMAGE_TAGS: ${{ matrix.tags }}
          IMAGE_REPOS: ${{ env.REGISTRIES }}
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      - name: Logout from GitHub Container Registry
        run: skopeo logout ghcr.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Logout from Quay.io
        run: skopeo logout quay.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Logout from Docker Hub
        run: skopeo logout docker.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
