name: Stable CI

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  REGISTRIES: ghcr.io,docker.io,quay.io
  REGISTRY_AUTH_FILE: ./auth.json

jobs:
  copy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: alpine3.15
            tags: |
              <full-ver>-alpine3.15
              <full-ver>-alpine
              <minor-ver>-alpine3.15
              <minor-ver>-alpine
              <major-ver>-alpine3.15
              <major-ver>-alpine
              alpine3.15
              alpine
          - os: alpine3.14
            tags: |
              <full-ver>-alpine3.14
              <minor-ver>-alpine3.14
              <major-ver>-alpine3.14
              alpine3.14
          - os: bullseye
            tags: |
              <full-ver>-bullseye
              <minor-ver>-bullseye
              <major-ver>-bullseye
              bullseye
          - os: slim-bullseye
            tags: |
              <full-ver>-slim-bullseye
              <minor-ver>-slim-bullseye
              <major-ver>-slim-bullseye
              slim-bullseye
          - os: buster
            tags: |
              <full-ver>-buster
              <full-ver>
              <minor-ver>-buster
              <minor-ver>
              <major-ver>-buster
              <major-ver>
              buster
              latest
          - os: slim-buster
            tags: |
              <full-ver>-slim-buster
              <full-ver>-slim
              <minor-ver>-slim-buster
              <minor-ver>-slim
              <major-ver>-slim-buster
              <major-ver>-slim
              slim-buster
              slim
    steps:
      - uses: actions/checkout@v2

      - name: Check upstream manifests changed
        id: upstream
        run: echo ::set-output name=RESULT::$(bash stable/check-changed.sh)
        env:
          IMAGE_OS: ${{ matrix.os }}

      - name: Login to GitHub Container Registry
        run: skopeo login --username=${{ github.repository_owner }}
                          --password='${{ secrets.GITHUB_TOKEN }}'
                    ghcr.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Login to Quay.io
        run: skopeo login --username=instrumentisto+bot
                          --password='${{ secrets.QUAYIO_ROBOT_TOKEN }}'
                    quay.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Login to Docker Hub
        run: skopeo login --username=instrumentistobot
                          --password='${{ secrets.DOCKERHUB_BOT_PASS }}'
                    docker.io
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      # https://github.com/containers/podman/issues/10112
      - name: Fix Podman's containers storage
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf "[storage.options]\nmount_program=\"/usr/bin/fuse-overlayfs\""\
                 > ~/.config/containers/storage.conf

      - name: Copy image
        run: bash stable/copy.sh
        env:
          IMAGE_OS: ${{ matrix.os }}
          IMAGE_TAGS: ${{ matrix.tags }}
          IMAGE_REPOS: ${{ env.REGISTRIES }}
        if: ${{ contains(steps.upstream.outputs.RESULT, 'CHANGED') }}

      - name: Logout from GitHub Container Registry
        run: skopeo logout ghcr.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Logout from Quay.io
        run: skopeo logout quay.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
      - name: Logout from Docker Hub
        run: skopeo logout docker.io
        if: ${{ always()
                && contains(steps.upstream.outputs.RESULT, 'CHANGED') }}
