name: Stable CI

on:
  schedule:
    - cron: "7 */12 * * *"

env:
  NAME: rust
  REGISTRY_AUTH_FILE: ./auth.json

jobs:
  copy:
    strategy:
      fail-fast: false
      matrix:
        registry: ["ghcr.io", "docker.io", "quay.io"]
        os:
          - alpine3.16
          - alpine3.15
          - bullseye
          - slim-bullseye
          - buster
          - slim-buster
        include:
          - os: alpine3.16
            tags: |
              <full-ver>-alpine3.16
              <full-ver>-alpine
              <minor-ver>-alpine3.16
              <minor-ver>-alpine
              <major-ver>-alpine3.16
              <major-ver>-alpine
              alpine3.16
              alpine
          - os: alpine3.15
            tags: |
              <full-ver>-alpine3.15
              <minor-ver>-alpine3.15
              <major-ver>-alpine3.15
              alpine3.15
          - os: bullseye
            tags: |
              <full-ver>-bullseye
              <full-ver>
              <minor-ver>-bullseye
              <minor-ver>
              <major-ver>-bullseye
              <major-ver>
              bullseye
              latest
          - os: slim-bullseye
            tags: |
              <full-ver>-slim-bullseye
              <full-ver>-slim
              <minor-ver>-slim-bullseye
              <minor-ver>-slim
              <major-ver>-slim-bullseye
              <major-ver>-slim
              slim-bullseye
              slim
          - os: buster
            tags: |
              <full-ver>-buster
              <minor-ver>-buster
              <major-ver>-buster
              buster
          - os: slim-buster
            tags: |
              <full-ver>-slim-buster
              <minor-ver>-slim-buster
              <major-ver>-slim-buster
              slim-buster
    runs-on: ubuntu-latest
    steps:
      # Skip if this is fork and no credentials are provided.
      - id: skip
        run: echo "no=${{ !(
               github.repository_owner != 'instrumentisto'
               && ((matrix.registry == 'quay.io'
                    && secrets.QUAYIO_ROBOT_USER == '')
                || (matrix.registry == 'docker.io'
                    && secrets.DOCKERHUB_BOT_USER == ''))
             ) }}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        if: ${{ steps.skip.outputs.no == 'true' }}

      - name: Check upstream manifests changed
        id: upstream
        run: echo "result=$(bash stable/check-changed.sh)"
             >> $GITHUB_OUTPUT
        env:
          IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ env.NAME }}
          IMAGE_OS: ${{ matrix.os }}
        if: ${{ steps.skip.outputs.no == 'true' }}

      - name: Login to ${{ matrix.registry }} container registry
        run: skopeo login --username='${{ (matrix.registry == 'docker.io'
                                           && secrets.DOCKERHUB_BOT_USER)
                                       || (matrix.registry == 'quay.io'
                                           && secrets.QUAYIO_ROBOT_USER)
                                       || github.repository_owner }}'
                          --password='${{ (matrix.registry == 'docker.io'
                                           && secrets.DOCKERHUB_BOT_PASS)
                                       || (matrix.registry == 'quay.io'
                                           && secrets.QUAYIO_ROBOT_TOKEN)
                                       || secrets.GITHUB_TOKEN }}'
                    ${{ matrix.registry }}
        if: ${{ steps.skip.outputs.no == 'true'
             && contains(steps.upstream.outputs.result, 'CHANGED') }}

      - name: Copy image
        run: bash stable/copy.sh
        env:
          IMAGE: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ env.NAME }}
          IMAGE_OS: ${{ matrix.os }}
          IMAGE_TAGS: ${{ matrix.tags }}
        if: ${{ steps.skip.outputs.no == 'true'
             && contains(steps.upstream.outputs.result, 'CHANGED') }}

      - name: Logout from ${{ matrix.registry }} container registry
        run: skopeo logout ${{ matrix.registry }}
        if: ${{ always()
             && steps.skip.outputs.no == 'true'
             && contains(steps.upstream.outputs.result, 'CHANGED') }}
